runner:
  vale:
    cmd: vale . --output=JSON
    format: json
    errorformat:
      - '%f:%l:%c:%tarning: %m'
      - '%f:%l:%c:%trror: %m'
      - '%f:%l:%c:%tote: %m'
    level: warning
    name: "Vale"
