extends: substitution

message: "Avoid Latin abbreviations: '%s'. Consider using 'for example', 'that is', 'and so forth', or 'such as'."
level: suggestion
swap:
  - e.g.: for example
  - eg: for example
  - i.e.: for example
  - i.e.: that is
  - etc.: and so on
  - N.B.: Note

action:
  name: replace
  params:
    - for example
    - that is
    - and so on
    - Note
