name: Vale Linter
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Required for accessing repository content
  pull-requests: write  # Required for creating review comments
  checks: write  # Required for creating GitHub checks
  
jobs:
  vale:
    name: vale action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.28.0/vale_2.28.0_Linux_64-bit.tar.gz
          mkdir bin && tar -xvzf vale_2.28.0_Linux_64-bit.tar.gz -C bin
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run Vale
        run: |
          mkdir -p tmp
          vale . --output=JSON > tmp/vale_output.json 2> tmp/vale_error.log || true
          echo "Vale output:"
          cat tmp/vale_output.json || echo "No output file generated"
          echo "Vale errors:"
          cat tmp/vale_error.log || echo "No errors captured"



