name: Vale Linter
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Required for accessing repository content
  pull-requests: write  # Required for creating review comments
  checks: write  # Required for creating GitHub checks
  
jobs:
  vale:
    name: vale action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

        
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.27.0/vale_2.27.0_Linux_64-bit.tar.gz
          tar -xvzf vale_2.27.0_Linux_64-bit.tar.gz
          sudo mv vale /usr/local/bin/vale
      
      - name: Run reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      
      - name: Run Vale with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vale --output-file=vale-output.txt **/*.md
          cat vale-output.txt | reviewdog -f=vale -reporter=github-pr-review
