name: Vale Linter
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Required for accessing repository content
  pull-requests: write  # Required for creating review comments
  checks: write  # Required for creating GitHub checks
  
jobs:
  vale:
    name: vale action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        
      - name: Get Changed Files
        id: get_changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.md
          separator: ","
      - name: Print Changed Markdown Files
        run: |
          echo "Changed markdown files: ${{ steps.get_changed_files.outputs.all_changed_files }}"

      - name: Vale Action
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.get_changed_files.outputs.all_changed_files }}
          separator: ","
          filter_mode: diff_context
          reporter: github-pr-review
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Convert Vale Output to rdformat
        run: |
          vale --output=rdjson ${{ steps.get_changed_files.outputs.all_changed_files }} > vale_output.rdjson
          echo "Vale Output in rdjson format:"
          cat vale_output.rdjson
