name: Vale Linter
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write  # Required for accessing repository content
  pull-requests: write  # Required for creating review comments
  checks: write  # Required for creating GitHub checks
  
jobs:
  vale:
    name: vale action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        
      - name: Get Changed Files
        id: get_changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.md
          separator: ","
      - name: Print Changed Markdown Files
        run: |
          echo "Changed markdown files: ${{ steps.get_changed_files.outputs.all_changed_files }}"

      - name: Vale Action
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.get_changed_files.outputs.all_changed_files }}
          separator: ","
          filter_mode: diff_context
          reporter: github-pr-review
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Convert to Reviewdog RDFormat
        id: convert_to_rdformat
        run: |
          changed_files="${{ steps.get_changed_files.outputs.all_changed_files }}"
          IFS=',' read -ra files <<< "$changed_files"
          for file in "${files[@]}"; do
            echo "{\"source\":\"$file\",\"message\":\"File changed.\",\"location\":{\"path\":\"$file\",\"range\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":1}}}}" >> rdformat_output.json
          done

      - name: Print RDFormat Output
        run: |
          cat rdformat_output.json
